### PR TITLE
#127 Upped dependencies/ removed warnings

### PR DESCRIPTION
**Pull request by GerwinBosch**
# Changelist

Changed url's from okfn to linkeddata.es

# Fixed issues

#127

### CODE REVIEW

**Comment by reinvantveer** [comment]
Sorry @GerwinBosch the CI didn't run successfully

**Comment by GerwinBosch** [comment]
I'm not really sure why. There seems to be something wrong with the Travis configuration. If someone else can look into that it would be great

**Comment by GerwinBosch** [comment]
\o/ after a lot of work, the CI runs again. However it seems that the almere virtuoso endpoint is offline, can you guys take a look at that?

**Comment by reinvantveer** [comment]
Approved!

**Comment by reinvantveer** [comment]
:rocket:

**Pull request merged**
